"""Chronicle enums — T010 (Phase 1a).

Defines Chronicle-specific enums not already in Relic core.
Enum source-of-truth per enum esistenti:
  - PrivacyLevel      → relic.persistence
  - ConsentType      → relic.control.consent
  - IncidentSeverity  → relic.control.incident
  - IncidentStatus    → relic.control.incident
  - ArtifactType      → relic.artifacts.types
  - CorrectionType    → relic.correction.propagation

Module: relic.chronicle.enums
Version: chronicle-enums/v1
"""
from __future__ import annotations

from enum import Enum


class EventCategory(str, Enum):
    """Category of event — determines retention, visibility, and processing path."""

    MESSAGE = "message"
    MODEL = "model"
    TOOL = "tool"
    MEMORY = "memory"
    PROFILE = "profile"
    DECISION = "decision"
    ARTIFACT = "artifact"
    SAFETY = "safety"
    PRIVACY = "privacy"
    CONSENT = "consent"
    ADMIN = "admin"
    EVAL = "eval"
    BACKGROUND = "background"
    ERROR = "error"
    STATE_SNAPSHOT = "state_snapshot"
    PROVENANCE = "provenance"


class RetentionPolicy(str, Enum):
    """How long an event/decision/snapshot is retained before reaper considers deletion."""

    EPHEMERAL = "ephemeral"  # < 1h, auto-deleted by reaper
    SHORT_30D = "short_30d"  # 30 days
    STANDARD_365D = "standard_365d"  # 1 year (default)
    EXTENDED_RESEARCH = "extended_research"  # 3 years, researcher-only
    LEGAL_HOLD = "legal_hold"  # never auto-delete, requires explicit removal


class VisibilityLevel(str, Enum):
    """Who can access this event/decision/snapshot via Chronicle CLI/readers."""

    RESEARCHER = "researcher"  # default, researcher-only
    ADMIN = "admin"  # admin-level access (includes researcher)
    SUBJECT_EXPORT = "subject_export"  # includable in GDPR export to subject


class ReasoningCapture(str, Enum):
    """How much reasoning/Chain-of-Thought detail is captured in the event payload."""

    NONE = "none"  # no reasoning captured
    METRICS_ONLY = "metrics_only"  # only numeric metrics (latency, tokens, etc.)
    REDACTED_SUMMARY = "redacted_summary"  # human-readable summary only (≤ 280 chars)
    RAW_RESEARCHER_ONLY = "raw_researcher_only"  # full raw CoT, researcher-only, no subject export


class ProximityOrder(str, Enum):
    """PROV-O relation types for provenance edges.

    References:
      - https://www.w3.org/TR/prov-o/
      - https://www.w3.org/TR/prov-dm/
    """

    USED = "used"  # Entity was used by Activity
    WAS_GENERATED_BY = "wasGeneratedBy"  # Entity was generated by Activity
    WAS_DERIVED_FROM = "wasDerivedFrom"  # Entity was derived from another Entity
    WAS_INFORMED_BY = "wasInformedBy"  # Activity was informed by Entity
    WAS_ASSOCIATED_WITH = "wasAssociatedWith"  # Agent was associated with Activity
    ACTED_ON_BEHALF_OF = "actedOnBehalfOf"  # Agent acted on behalf of another Agent
    HAD_MEMBER = "hadMember"  # Collection had member Entity
    WAS_TRIGGERED_BY = "wasTriggeredBy"  # Activity was triggered by Entity
    WAS_CONTROLLED_BY = "wasControlledBy"  # Activity was controlled by Agent


class ValidationStatus(str, Enum):
    """Validation status for decision records."""

    PENDING = "pending"  # not yet validated
    VALIDATED = "validated"  # cross-checked and confirmed
    SUPERSEDED = "superseded"  # replaced by a newer decision
    DISPUTED = "disputed"  # challenged, under review
    FAILED = "failed"  # validation check failed


class AccessKind(str, Enum):
    """Type of access logged in chronicle_access_log."""

    QUERY = "query"
    TIMELINE = "timeline"
    DECISION = "decision"
    SNAPSHOT = "snapshot"
    PROVENANCE = "provenance"
    EXPORT = "export"
    DELETE = "delete"
    REAPER_RUN = "reaper_run"
    REPLAY = "replay"
    REPORT = "report"
    CONFIG_CHANGE = "config_change"
    FORENSIC_MODE = "forensic_mode"
    ENCRYPTION_KEY_ACCESS = "encryption_key_access"


class Severity(str, Enum):
    """Severity level for events and audit log entries."""

    DEBUG = "debug"
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"
